language: scala
scala: 2.12.10
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "NlWwYTyNyZ+z2Kv0XKWKgEC2u+XHnyio91drKwCZ+NeAcoJfXjoMv4bD8hzx1kOvwmD+LXUnZQdzp5+VgNuh7Oqk3wl+PXIPXFrvgHRCZPdWTu21MJElB8FwdWvPV9yYuME1i1be4VTceyi/YxNKRKfXTwLUKQv3sy6lFV8rM3nyp8LV0d64Xu/X6rDy8fnDd+zHMxShLP3cwrEWh+3KVUDZt2qaRe8PdzQWFe42Gn0Ai2BnZ1+84+T4hGMJl5kcYqYohj1ibXst7cbHVKMbwbLf+ePjrQdObIIgP08t1GhIzTmkJJA309MkbPCGlwuT4zMpAcY/E8kcgz8H2UODJAZQUOz1AneAIVJ5rr0SazjCIT6neNDXCvqbwFUkvHpqjq0pMYI6qJtJxQfavT7vuPlRGF6BqesgvypdpGFEdGnKcWF9Jkx1Cyr9ywX6pQbFtZ0uF+gjJPePirwiMCP1pQC+V23JL1Dgy4PemeMTEewZ9Po4l+jhmNk4D5QXrrygAq3dICWkImy6KzkMzkpumo25+10MIalLTMZzhDbwlEhiGDbQ0YdjlqLMN8DsueloBxPY0lxDSsvUgxwcl8DuBfMi4mf7v58CyrG5iMstY4BGPGV7U8KQ3FIWbefxVwJW4NAzhuACn0QXUKTpF5M7ViNzbQ9AEgMI2JQ6F95OkH8="
    # GITHUB_TOKEN
    - secure: "cJLEf6YD+Xna//LCdMr0AuzC66Ia/OT/kosxyR/Q4D1vxhdb0sH4ZUHkMjYQSa1XEk0Mw7AqgT/gQ4cO5iTRq/QHRz7qZ/tnKRtFIVamk2/jhm4puD+2m7/pLUzr3/DC/upRCFmcEbdzGZyFuFrjzw2wRcYB8fTAw14em+CqW4cSn5QbR5EcQtqFyDu7QW5yhOWoMiS1091zi0BFieYXXPv8R4TGtkSyrGTuSuvT2ktAlWcZTZkLOULkLWN1AQMXlhlfOJpWZq0BNFazs5MzLh2fUkRGNsHbt7Sa+PkCVmixK7EVkKJT9McEYFNG+N+Joxb36TTx0Boq29zU9GEFRD1XjMinTyjz7W4w6VDhgWplwHduSnajrwAw+QQPKK5ChhqfsgwamKH2WgRl1kBt1EN1OYnr2w+k1qer0nEqocY3gAuL7YF+Tx3/u0FrMLzrPnVd6V/zCvsKvSO5WayhltY8bjvJ4PX7bd00xEI2JHktmmLPtnljxFsGXAz4YBpzYOa+pNe1YPer0G3/yipXwl13ZapIDn1pgDVtoGA3mUKVL+fOOInQ66LWJvvQpDJQJGnTMCyF2pkp6R4MVAeG/lcScb0WczvOYWpQO7xC10zCH3Bg4A6nuzqRYqXUSqYVe6WK0EgWKUoPxVVGQkUWi4F1c+AtqqenWBdKK6+6NXE="
    # GITHUB_ACCESS_TOKEN
    - secure: "eYJNFvIBxZmtcoMAYH7AULX3BIvTQejKlJFVOPcMmM9U2AEnOaRljA5bhz/Byj1DwyT/DhWYDBt8grn6PHa07506QY6bHC+YGdFImP6VznOfm+ZryTkfTxkUJqdg56O7chbsDUcHw+TkQ+R+u+Sj4KKa5Db+LcMBJmUgHG7lXWRJbNIShpZZFSAR8f9rYNjZFIVqmb9+vhZFrml/mPXbnGH9qrws+MKk+4j6PUhA+hrUqZq1AXCpb2RoMejJYx8qq6icZhG63yPBO0JsUKH33FouDeh9YmpjKsV8o2BHWdMNvl0dM72oN8OHMir0X0wTQiiBwopq+gV5r3GETKWESr3DdUJO34WIubbQu2deAk0x30MVC9ui6U47HOMBGE8xQS+J9JzGbp1I2Ho/xnpq0s262PUz+kQbjpvqHLVCvFx/GEAFRKqZjZB4fJhOGKxJP0FsG76NwX79nB0CkIZazoRLNBIRgQEt3D4bm6jqsDbGQYUz0EksgUQ7aRmWa2VAfq3gyk2yfHePUSONz+wIQ0JdZ3RxM23hW+nLjWOlTJq/g1XpJ+oINQHTylhGRwneS9ddf7y4yd7Ezu9XU/o3SkXaQ7UTcjyorhKUCrJAOpbZi/khHCvvzldq/mhuG+CPB4ogmQLKim3a0mhdc0GMO3v5XMse+UtsbMD0y0+7iWg="

    # DISCORD_WEBHOOK_TOKENS
    - secure: "gHHSkME7N5KAtbTzqMdPoU2lRzRM9vEe3Bq0L/IzTuH4YGXkB2w/+rHRDIdXftlwHn38NYrkBatsw3iWjA/ntvxGb6FGzpvVaho8EeiGF7TvvmCmyMmk3ZxmxXmrzbaKG/JQppZcTnceIg1cjWkdpC8MT05ApTxWb9yD5mM+XQuQht05n/h6YyQeGLXMbrz7MqLFp3u7W8BTtl9ig7QIYiYgCfnF7cQ2jpIcWMh1eeLW7Lvhvm3R+eiUg0pC7Auws9JNv6NJzJckA4PvIiNL2EXXUzql5tnUFHFMpxztGug6Lm7ZRsiWHYvyeT3mYbx44GfpmjIG6uF1mcrwUGMA/rllsVlL2XMXwMD7FLNLwidWq3nIGD43pRW8rXhHIu3iGCjHnu2nADn2r1POyJG0h5tPUn909blT0Y/pGqWBa4w3ByIYqnfmZ7kUhojapdVB/t6s6qImvSHjknjPH4KD9jb6zirvknjmlrf5og9gsn0IPaGksXQ/WDFCoGRejtzbHjQVVvY3SQAC9A+1kBgGGFymjLrQDc8RqTgsH0DPo3Ze7ECBbYu2DZgTtbIRuE477we34sKXiWaKEjt9jJTHgkdoslWNutC/KKX7aneXeyhxQ2Lya85wmqVgR9wfQimAKJy18WT0x1GgM/EzzAkKuyfNC7sOZLN99IA/JQlAKpo="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-redshift';
        bumpInDownstream() { echo $1 > slamdata-destination-redshift-version; }
        export -f bumpInDownstream
        scripts/bumpDependentProject slamdata slamx bumpInDownstream
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
